USE [master]
GO

/****** Object:  Database [Crime]    Script Date: 11.03.2015 14:25:41 ******/
CREATE DATABASE [Crime]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Crime', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV01\MSSQL\DATA\Crime.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Crime_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.DEV01\MSSQL\DATA\Crime_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Crime] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Crime].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Crime] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Crime] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Crime] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Crime] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Crime] SET ARITHABORT OFF 
GO

ALTER DATABASE [Crime] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Crime] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Crime] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Crime] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Crime] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Crime] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Crime] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Crime] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Crime] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Crime] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Crime] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Crime] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Crime] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Crime] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Crime] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Crime] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Crime] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Crime] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Crime] SET RECOVERY FULL 
GO

ALTER DATABASE [Crime] SET  MULTI_USER 
GO

ALTER DATABASE [Crime] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Crime] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Crime] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Crime] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Crime] SET  READ_WRITE 
GO

